// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiqfmoezdmfgoiijlzud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpcWZtb2V6ZG1mZ29paWpsenVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDM1MTgsImV4cCI6MjA1ODY3OTUxOH0.IIlLzqXa3Zk6ADuR2bE5mEaKpWxzVQfP0A5WxA3vI8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);